# Generated by Django 2.0.8 on 2019-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSSpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64, verbose_name='Слово')),
                ('speech', models.CharField(max_length=64, verbose_name='Произношение')),
            ],
        ),
    ]
