# Generated by Django 2.0.8 on 2019-01-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('session_id', models.CharField(max_length=64)),
                ('message_id', models.IntegerField()),
                ('ask', models.CharField(max_length=1024)),
                ('ans', models.CharField(max_length=1024)),
            ],
        ),
    ]
